geo_dash: raster.o events.o effects.o psg.o music.o model.o render.o bitmaps.o input.o GeoDash.o rastasm.o clr_qk.o m_splash.o Gosplash.o w_splash.o
	cc68x -g raster.o events.o model.o effects.o psg.o music.o render.o bitmaps.o input.o GeoDash.o rastasm.o clr_qk.o m_splash.o Gosplash.o w_splash.o -o geo_dash

GeoDash.o: GeoDash.c GeoDash.h	
	cc68x -g -c GeoDash.c
music.o: music.c music.h
	cc68x -g -c music.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c


effects.o: effects.c effects.h
	cc68x -g -c effects.c
	
input.o: input.c input.h
	cc68x -g -c input.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

events.o: events.c events.h
	cc68x -g -c events.c

model.o: model.c model.h
	cc68x -g -c model.c

render.o: render.c render.h
	cc68x -g -c render.c  	 	

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c 
	
	
m_splash.o: m_splash.c m_splash.h
	cc68x -g -c m_splash.c 

	
Gosplash.o: Gosplash.c Gosplash.h
	cc68x -g -c Gosplash.c

	
w_splash.o: w_splash.c w_splash.h
	cc68x -g -c w_splash.c

clr_qk.o: clr_qk.s
	gen -L2 -D clr_qk.s

rastasm.o: rastasm.s
	gen -L2 -D rastasm.s

clean:
	$(RM) *.o
	
